<div class="container py-5">
    <div class="input-group">
        <form method="post">

            <input type="search" id="search_box" name="search_box" class="form-control" />

            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>
    <div class="row text-center text-white mb-5">
        <div class="col-lg-7 mx-auto">
            <h1 class="display-4">Book List</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <!-- List group-->
            <ul class="list-group shadow">
                <!-- list group item-->
                <?php
               
                    foreach ($books as $book) {
                        echo '<li class="list-group-item">
                            <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                                <div class="media-body order-2 order-lg-1">
                                    <h5 class="mt-0 font-weight-bold mb-2">' . $book['title'] . '</h5>
                                    <div class="d-flex align-items-center justify-content-between mt-1">
                                        <h6 class="font-weight-bold my-2">' . $book['author_name'][0] . '</h6>
                                    </div>
                                </div>
                                <a href="http://localhost:8080/index/singlepage/' . $book['cover_edition_key'] . '">
                                <img src="//covers.openlibrary.org/b/olid/' . $book['edition_key'][0] . '.jpg" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                                </a>
                                </div> <!-- End -->
                        </li>';
                    }
                
                ?>
                <!-- End -->
            </ul> <!-- End -->
        </div>
    </div>
</div>